version: "3.8"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./app:/app
      - ./tests:/app/tests
    env_file:
      - .env

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"